version: '3.7'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
        target: base
    volumes:
        - ./src:/home/node/app/src
        - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
        - '3002'
    ports:
        - '3002:3002'
    command: npm run dev